name: on_push

on:
  push:
    branch:
      - "**" # This will run on all branches, and must be quoted to be handled by yaml
  #schedule:
  #  - cron: '*/10 * * * *' # This will run every 10th minute. Calculated with https://crontab.guru/

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    #variable para indicar que chromedriver correra en linux (Ver base test)
    env:
      RUNNER_OS: true
      HEADLESS_CHROME: true
      BUILDEVENT_FILE: './buildevents.txt' # This is root of our repository

    steps:
      # set a start time
      - name: Set start time
        run: echo "START_SEC=$(date +%s)" >> $GITHUB_ENV
      - uses: kvrhdn/gha-buildevents@v1
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: my-build-pipeline
          job-status: ${{ job.status }}
      - uses: actions/checkout@v2
      # install java
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 16
      # Introduce start of span
      - name: Telemetry start - Maven tests
        if: always()
        run: |
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
          echo "STEP_ID=run-maven-tests" >> $GITHUB_ENV
      - name: Run test with maven
        working-directory: webdriver_java
        run: mvn test
      # Finalise span
      - name: Telemetry - Collect build data
        working-directory: webdriver_java
        env:
          PUSHGATEWAY_URL: ${{ secrets.PUSHGATEWAY_URL }}
          BUILDEVENT_FILE: ../${{ env.BUILDEVENT_FILE }}
        if: always()
        run: |
          echo "github_actions_total_duration $(expr $(date +%s) - ${START_SEC})" | curl --data-binary @- ${PUSHGATEWAY_URL}/metrics/job/github_actions
          ./resources/test_result_script.sh
          buildevents step $TRACE_ID $STEP_ID $STEP_START $STEP_ID